ALTER TABLE INGRESSO_VENDIDO
DROP FOREIGN KEY fk_EVENTO_has_CLIENTE_EVENTO;





ALTER TABLE INGRESSO_VENDIDO
ADD CONSTRAINT fk_EVENTO_has_CLIENTE_EVENTO
FOREIGN KEY (EVENTO_idEvento)
REFERENCES EVENTO(idEvento)
ON DELETE CASCADE
ON UPDATE NO ACTION;